if: tag IS present OR type = pull_request OR (branch = master AND type = push)   # we only CI the master, tags and PRs

language: python
cache: pip
dist: xenial
python:
  - "3.5"
  - "3.6"

env:
  - DB=mongodb DATABASE_URL=mongodb://localhost:27017/alerta5
  - DB=postgres DATABASE_URL=postgres://localhost:5432/alerta5

services:
  - mongodb
  - postgresql

addons:
  postgresql: "9.5"

before_script:
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'DROP DATABASE IF EXISTS alerta5;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'CREATE DATABASE alerta5;' -U postgres; fi"

install:
  - pip install .
  - pip install -r requirements.txt
  - pip install mypy==0.620

script:
  - python -m mypy alerta/
  - nosetests --verbosity=3 tests/*
